home:
  path: /
  controller: App\Controller\BlogController::home

post:
  path: /post/{id}
  controller: App\Controller\BlogController::post

category:
  path: /category/{id}
  controller: App\Controller\BlogController::category